2019-05-29 18:08:35 ERROR (SyncWorker_0) [homeassistant.util.yaml] YAML file /config/configuration.yaml contains duplicate key "tts". Check lines 30 and 54.
2019-05-29 18:08:40 ERROR (MainThread) [homeassistant.components.device_tracker] Unable to load /config/known_devices.yaml: Config file not found: /config/known_devices.yaml
2019-05-29 19:08:38 ERROR (MainThread) [homeassistant.components.updater] Got unexpected response: None
2019-05-30 01:09:21 ERROR (MainThread) [homeassistant.components.yr.sensor] Retrying in 15 minutes: Cannot connect to host aa015h6buqvih86i1.api.met.no:443 ssl:None [Try again]
2019-05-30 01:24:27 ERROR (MainThread) [homeassistant.components.yr.sensor] Retrying in 16 minutes: Cannot connect to host aa015h6buqvih86i1.api.met.no:443 ssl:None [Try again]
2019-05-30 01:40:33 ERROR (MainThread) [homeassistant.components.yr.sensor] Retrying in 16 minutes: Cannot connect to host aa015h6buqvih86i1.api.met.no:443 ssl:None [Try again]
2019-05-30 01:56:39 ERROR (MainThread) [homeassistant.components.yr.sensor] Retrying in 19 minutes: Cannot connect to host aa015h6buqvih86i1.api.met.no:443 ssl:None [Try again]
2019-05-30 05:15:59 ERROR (MainThread) [homeassistant.components.yr.sensor] Retrying in 19 minutes: Cannot connect to host aa015h6buqvih86i1.api.met.no:443 ssl:None [Try again]
2019-05-30 05:35:05 ERROR (MainThread) [homeassistant.components.yr.sensor] Retrying in 20 minutes: Cannot connect to host aa015h6buqvih86i1.api.met.no:443 ssl:None [Try again]
2019-05-30 05:55:11 ERROR (MainThread) [homeassistant.components.yr.sensor] Retrying in 19 minutes: Cannot connect to host aa015h6buqvih86i1.api.met.no:443 ssl:None [Try again]
2019-05-30 06:14:17 ERROR (MainThread) [homeassistant.components.yr.sensor] Retrying in 20 minutes: Cannot connect to host aa015h6buqvih86i1.api.met.no:443 ssl:None [Try again]
2019-05-30 06:34:23 ERROR (MainThread) [homeassistant.components.yr.sensor] Retrying in 17 minutes: Cannot connect to host aa015h6buqvih86i1.api.met.no:443 ssl:None [Try again]
2019-05-30 06:51:29 ERROR (MainThread) [homeassistant.components.yr.sensor] Retrying in 17 minutes: Cannot connect to host aa015h6buqvih86i1.api.met.no:443 ssl:None [Try again]
2019-05-30 07:08:35 ERROR (MainThread) [homeassistant.components.yr.sensor] Retrying in 20 minutes: Cannot connect to host aa015h6buqvih86i1.api.met.no:443 ssl:None [Try again]
2019-05-30 07:28:41 ERROR (MainThread) [homeassistant.components.yr.sensor] Retrying in 15 minutes: Cannot connect to host aa015h6buqvih86i1.api.met.no:443 ssl:None [Try again]
2019-05-30 07:43:43 ERROR (MainThread) [homeassistant.components.yr.sensor] Retrying in 19 minutes: https://aa015h6buqvih86i1.api.met.no/weatherapi/locationforecast/1.9/?lat=-6.1741&lon=106.8296&msl=0 returned 503
2019-05-30 19:08:39 ERROR (MainThread) [homeassistant.components.updater] Got unexpected response: None
2019-05-30 21:03:45 ERROR (MainThread) [homeassistant.components.yr.sensor] Retrying in 16 minutes: Cannot connect to host aa015h6buqvih86i1.api.met.no:443 ssl:None [Try again]
2019-05-31 19:08:38 ERROR (MainThread) [homeassistant.components.updater] Got unexpected response: None
